package com.example.medibin.bindata;


import com.example.medibin.R;

public class BloodBankData {

    public static String[] nameArray = {
            "Face Mask",
            "Ampules",
            "IV Cannula",
            "Biopsy Specimen",
            "Petridish with Culture",
            "Cap",
            "Blood Smear",
            "Culture and Stock of Infectious Agent",
            "Culture Tubes",
            "Disinfectant",
            "Empty Medicinal Glassware",
            "Expired Medicines",
            "Smear",
            "Farmalin",
            "Fixed Needle Vaccine Syring",
            "Glass Dropper",
            "Gloves Pair",
            "Hospital Disinfectant",
            "Hospital Grown",
            "IM Needle",
            "Blood Bags",
            "Kidner Tray Plastic",
            "Lab Culture",
            "Laboratory Glassware",
            "LP Needle",
            "Medicine Vials and Ampules",
            "Needles",
            "Aspirated Body Fluids",
            "Pipette",
            "Plastic Covers",
            "Soiled Cotton",
            "Plunger of Syringe",
            "Shoe Cover",
            "Slide & Cover Slip",
            "Plastic Disposable Bin",
            "Soiled Cotton Guaze",
            "Microscope Slides",
            "Specimen",
            "Stool Iodine and Saline Mount",
            "Syringe without Needle",
            "Test Tubes",
            "Vaccine",
            "Vacutainer Needle",
            "Vacutainer",
            "Venflon",
            "Vials",
            "Aspirated Secretion",
            "Broken or Discarded Glassware",
            "Disposable Shoe Cover"


    };
    public static String[] versionArray = {
            "3",
            "1",
            "4",
            "3",
            "4",
            "3",
            "1",
            "3",
            "4",
            "3",
            "1",
            "3",
            "1",
            "3",
            "4",
            "1",
            "2",
            "3",
            "3",
            "4",
            "3",
            "2",
            "4",
            "1",
            "4",
            "1",
            "4",
            "3",
            "1",
            "2",
            "3",
            "2",
            "3",
            "1",
            "2",
            "3",
            "1",
            "3",
            "1",
            "2",
            "1",
            "3",
            "4",
            "2",
            "4",
            "1",
            "3",
            "1",
            "3"


    };

    public static Integer[] drawableArray = {
            R.drawable.face_mask,
            R.drawable.ampules,
            R.drawable.iv_cannula,
            R.drawable.biopsy_specimen,
            R.drawable.petridish_with_culture,
            R.drawable.cap,
            R.drawable.blood_smear,
            R.drawable.culture_and_stock_of_infectious_agent,
            R.drawable.culture_tubes,
            R.drawable.disinfectant,
            R.drawable.empty_medicinal_glassware,
            R.drawable.expired_or_discarded_medicines,
            R.drawable.blood_smear,
            R.drawable.formalin,
            R.drawable.fixed_needle_vacine_syringe,
            R.drawable.glass_dropper,
            R.drawable.gloves_pair,
            R.drawable.hospital_disinfectant,
            R.drawable.hospital_gown,
            R.drawable.im_needle,
            R.drawable.blood_bags,
            R.drawable.kidner_tray_palstic,
            R.drawable.lab_culture,
            R.drawable.laboratory_glassware,
            R.drawable.lp_needle,
            R.drawable.medicine_vials_and_ampules,
            R.drawable.needles,
            R.drawable.aspirated_body_fluids,
            R.drawable.pipette,
            R.drawable.plastic_covers,
            R.drawable.soiled_cotton,
            R.drawable.plunger_of_syringe,
            R.drawable.shoe_cover,
            R.drawable.slides,
            R.drawable.plastic_disposable_bin,
            R.drawable.soiled_cotton_guaze,
            R.drawable.microscope_slides,
            R.drawable.specimen,
            R.drawable.stool_iodine_and_saline_mount,
            R.drawable.syringe_without_needle,
            R.drawable.test_tubes,
            R.drawable.vaccine,
            R.drawable.vacutainer_needle,
            R.drawable.vacutainer,
            R.drawable.venflon,
            R.drawable.vials,
            R.drawable.aspirated_secretion,
            R.drawable.broken_glassware,
            R.drawable.shoe_cover


    };

    public static Integer[] id_ = {0, 1};
}
