package com.example.medibin.bindata;


import com.example.medibin.R;

public class InfoData {

    public static String[] nameArray = {
            "Broken Glassware",
            "Face Mask",
            "Kidner Tray Plastic",
            "Nasogastic Tube",
            "Plastic Disposable Bin",
            "Lancet",
            "Oxygen Nebulizer mask",
            "Slides",
            "Syringe without Needle",
            "Vaccine vial",
            "Aspirated body Fluids",
            "Cap",
            "Empty Medical Glassware",
            "Fixed Needle syringe",
            "IV normal Saline Bottle",
            "Metal cap of Vials",
            "Plastic covers",
            "Soiled cotton guaze",
            "Tooth",
            "Vacutainer",
            "Blood Smear",
            "Cotton Guaze",
            "Empty Medicine Bottle Plastic",
            "Gloves Pair",
            "Suture Needle",
            "Ampules",
            "Antibiotic Injection",
            "Empty Medicinal Glassware",
            "Empty Syrup Bottle",
            "Blood Bags",
            "Expired Medicines",
            "Fixed Needle Syring",
            "Soiled Cotton",
            "Foleys Catheter",
            "Hospital Disinfectant",
            "Discarded Glassware",
            "Hospital Grown",
            "IM Needle",
            "Chemotherapy Drugs",
            "Insulin Syring",
            "IV Cannula",
            "IV Dextrose Bottle",
            "Medicine Vials and Ampules",
            "IV Fluids",
            "Soiled Dressing",
            "Nasogastric Tube",
            "Needles",
            "Soiled Mastress",
            "NG Tube",
            "Oxygen or Nebulizer Mask",
            "Plaster Cast",
            "IV Fluid Bag",
            "Plunger of Syringe",
            "Shoe Cover",
            "Specimen",
            "Uro-Bag",
            "Vaccine",
            "Vacutainer Needle",
            "IV Set",
            "Venflon",
            "Vials",
            "Antibiotic",
            "Ccine",
            "Pipette",
            "Fixed Needle Vaccine Syring",
            "Disinfectant",
            "Test Tubes",
            "Aborted Fetus",
            "Amputated Body Parts",
            "ET Tube",
            "Aspirated Secretion",
            "Biopsy Needle",
            "Biopsy Specimen",
            "Dialysis Catheter",
            "Blood Stained Cotton Guaze",
            "Bone Marrow Biopsy Needle",
            "Dental Implants",
            "Microscope Slides",
            "Human Anatomical Waste",
            "Liver Biopsy Needle",
            "LP Needle",
            "Metal Implants",
            "Metallic Body Implants",
            "Placenta",
            "Slide & Cover Slip",
            "Smear",
            "Tracheostomy Tube",
            "Surgical Blade  & Scalpel",
            "Metallic Body Implant",
            "Stained Cotton and Guaze pads",
            "Petridish with Culture",
            "Culture and Stock of Infectious Agent",
            "Culture Tubes",
            "Farmalin",
            "Glass Dropper",
            "Lab Culture",
            "Laboratory Glassware",
            "Stool Iodine and Saline Mount",
            "Broken or Discarded Glassware",
            "Disposable Shoe Cover",
            "Foley's Catheter",

    };
    public static String[] versionArray = {
            "1",
            "3",
            "2",
            "2",
            "2",
            "4",
            "2",
            "1",
            "2",
            "3",
            "3",
            "3",
            "1",
            "4",
            "2",
            "4",
            "2",
            "3",
            "3",
            "2",
            "1",
            "3",
            "2",
            "2",
            "4",
            "1",
            "3",
            "1",
            "1",
            "3",
            "3",
            "4",
            "3",
            "2",
            "3",
            "1",
            "3",
            "4",
            "3",
            "4",
            "4",
            "2",
            "1",
            "2",
            "3",
            "2",
            "4",
            "3",
            "2",
            "2",
            "3",
            "2",
            "2",
            "3",
            "3",
            "2",
            "3",
            "4",
            "2",
            "4",
            "1",
            "3",
            "3",
            "1",
            "4",
            "3",
            "1",
            "3",
            "3",
            "2",
            "3",
            "4",
            "3",
            "2",
            "3",
            "4",
            "1",
            "1",
            "3",
            "4",
            "4",
            "1",
            "1",
            "3",
            "1",
            "1",
            "2",
            "4",
            "1",
            "3",
            "3",
            "3",
            "3",
            "3",
            "1",
            "3",
            "1",
            "1",
            "1",
            "3",
            "2",


    };

    public static Integer[] drawableArray = {
            R.drawable.broken_or_discarded_glassware,
            R.drawable.face_mask,
            R.drawable.kidner_tray_palstic,
            R.drawable.nasogastric_tube,
            R.drawable.plastic_disposable_bin,
            R.drawable.lancet,
            R.drawable.oxygen_nebulizer_mask,
            R.drawable.slides,
            R.drawable.syringe_without_needle,
            R.drawable.vaccine_vial,
            R.drawable.aspirated_body_fluids,
            R.drawable.cap,
            R.drawable.empty_medicinal_glassware,
            R.drawable.fixed_needle_syringe,
            R.drawable.iv_normal_saline_bottle,
            R.drawable.metal_cap_of_vials,
            R.drawable.plastic_covers,
            R.drawable.soiled_cotton_guaze,
            R.drawable.tooth,
            R.drawable.vacutainer,
            R.drawable.blood_smear,
            R.drawable.cotton_guaze,
            R.drawable.empty_medicine_bottle_plastic,
            R.drawable.gloves_pair,
            R.drawable.sature_needle,
            R.drawable.ampules,
            R.drawable.antibiotic_injection,
            R.drawable.empty_medicinal_glassware,
            R.drawable.empty_syrup_bottles,
            R.drawable.blood_bags,
            R.drawable.expired_or_discarded_medicines,
            R.drawable.fixed_needle_syringe,
            R.drawable.soiled_cotton,
            R.drawable.foleys_catheter,
            R.drawable.hospital_disinfectant,
            R.drawable.broken_or_discarded_glassware,
            R.drawable.hospital_gown,
            R.drawable.im_needle,
            R.drawable.chemotherapydrugs,
            R.drawable.insulin_syringe,
            R.drawable.iv_cannula,
            R.drawable.iv_dextrose_bottle,
            R.drawable.medicine_vials_and_ampules,
            R.drawable.iv_fluids,
            R.drawable.soiled_dressing,
            R.drawable.nasogastric_tube,
            R.drawable.needles,
            R.drawable.soiled_matress,
            R.drawable.ng_tube,
            R.drawable.oxygen_or_nebulizer_mask,
            R.drawable.plaster_cast,
            R.drawable.iv_fluid_bag,
            R.drawable.plunger_of_syringe,
            R.drawable.shoe_cover,
            R.drawable.specimen,
            R.drawable.urobag,
            R.drawable.vaccine_syringe,
            R.drawable.vacutainer_needle,
            R.drawable.iv_set,
            R.drawable.venflon,
            R.drawable.vials,
            R.drawable.antibiotics,
            R.drawable.ccines,
            R.drawable.pipette,
            R.drawable.fixed_needle_vacine_syringe,
            R.drawable.disinfectant,
            R.drawable.test_tubes,
            R.drawable.aborted_fetus,
            R.drawable.amputated_body_parts,
            R.drawable.et_tube,
            R.drawable.aspirated_secretion,
            R.drawable.biopsy_needle,
            R.drawable.biopsy_specimen,
            R.drawable.dialysis_catheter,
            R.drawable.blood_stained_cotton_guaze,
            R.drawable.bone_marrow_biopsy_needle,
            R.drawable.dental_implants,
            R.drawable.microscope_slides,
            R.drawable.human_anatomical_waste,
            R.drawable.liver_biopsy_needle,
            R.drawable.lp_needle,
            R.drawable.metal_implants,
            R.drawable.metallic_body_implants,
            R.drawable.placenta,
            R.drawable.slides,
            R.drawable.blood_smear,
            R.drawable.tracheostomy_tube,
            R.drawable.surgical_blade_scalpel,
            R.drawable.metallic_body_implants,
            R.drawable.stained_cotton_and_guaze_pads,
            R.drawable.petridish_with_culture,
            R.drawable.culture_and_stock_of_infectious_agent,
            R.drawable.culture_tubes,
            R.drawable.formalin,
            R.drawable.glass_dropper,
            R.drawable.lab_culture,
            R.drawable.laboratory_glassware,
            R.drawable.stool_iodine_and_saline_mount,
            R.drawable.broken_glassware,
            R.drawable.shoe_cover,
            R.drawable.foleys_catheter,



    };

    public static Integer[] id_ = {0, 1, 2,3,4,5,6,7,8};
}
