package com.example.medibin.bindata;


import com.example.medibin.R;

public class InPatientWardData {

    public static String[] nameArray = {
            "Ampules",
            "Antibiotic Injection",
            "Blood Smear",
            "Cap",
            "Cotton Guaze",
            "Empty Medicinal Glassware",
            "Empty Medicine Bottle Plastic",
            "Empty Syrup Bottle",
            "Blood Bags",
            "Expired Medicines",
            "Fixed Needle Syring",
            "Soiled Cotton",
            "Foleys Catheter",
            "Broken Glassware",
            "Gloves Pair",
            "IV Normal Saline Bottle",
            "Hospital Disinfectant",
            "Discarded Glassware",
            "Plastic Covers",
            "Hospital Grown",
            "IM Needle",
            "Chemotherapy Drugs",
            "Insulin Syring",
            "IV Cannula",
            "Aspirated Body Fluids",
            "IV Dextrose Bottle",
            "Kidner Tray Plastic",
            "Lancet",
            "Medicine Vials and Ampules",
            "Metal Cap of Vials",
            "IV Fluids",
            "Soiled Dressing",
            "Nasogastric Tube",
            "Needles",
            "Soiled Mastress",
            "NG Tube",
            "Ccine",
            "Oxygen or Nebulizer Mask",
            "Plaster Cast",
            "IV Fluid Bag",
            "Plunger of Syringe",
            "Shoe Cover",
            "Specimen",
            "Suture Needle",
            "Syringe without Needle",
            "Uro-Bag",
            "Vaccine",
            "Vacutainer",
            "Vacutainer Needle",
            "IV Set",
            "Venflon",
            "Plastic Disposable Bin",
            "Vials",
            "Soiled Cotton Guaze",
            "Antibiotic",
    };
    public static String[] versionArray = {
            "1",
            "3",
            "1",
            "3",
            "3",
            "1",
            "2",
            "1",
            "3",
            "3",
            "4",
            "3",
            "2",
            "1",
            "2",
            "2",
            "3",
            "1",
            "2",
            "3",
            "4",
            "3",
            "4",
            "4",
            "3",
            "2",
            "2",
            "4",
            "1",
            "4",
            "2",
            "3",
            "2",
            "4",
            "3",
            "2",
            "3",
            "2",
            "3",
            "2",
            "2",
            "3",
            "3",
            "4",
            "2",
            "2",
            "3",
            "2",
            "4",
            "2",
            "4",
            "2",
            "1",
            "3",
            "3",
    };

    public static Integer[] drawableArray = {
            R.drawable.ampules,
            R.drawable.antibiotic_injection,
            R.drawable.blood_smear,
            R.drawable.cap,
            R.drawable.cotton_guaze,
            R.drawable.empty_medicinal_glassware,
            R.drawable.empty_medicine_bottle_plastic,
            R.drawable.empty_syrup_bottles,
            R.drawable.blood_bags,
            R.drawable.expired_or_discarded_medicines,
            R.drawable.fixed_needle_syringe,
            R.drawable.soiled_cotton,
            R.drawable.foleys_catheter,
            R.drawable.broken_glassware,
            R.drawable.gloves_pair,
            R.drawable.iv_normal_saline_bottle,
            R.drawable.hospital_disinfectant,
            R.drawable.broken_or_discarded_glassware,
            R.drawable.plastic_covers,
            R.drawable.hospital_gown,
            R.drawable.im_needle,
            R.drawable.chemotherapydrugs,
            R.drawable.insulin_syringe,
            R.drawable.iv_cannula,
            R.drawable.aspirated_body_fluids,
            R.drawable.iv_dextrose_bottle,
            R.drawable.kidner_tray_palstic,
            R.drawable.lancet,
            R.drawable.medicine_vials_and_ampules,
            R.drawable.metal_cap_of_vials,
            R.drawable.iv_fluids,
            R.drawable.soiled_dressing,
            R.drawable.nasogastric_tube,
            R.drawable.needles,
            R.drawable.soiled_matress,
            R.drawable.ng_tube,
            R.drawable.ccines,
            R.drawable.oxygen_or_nebulizer_mask,
            R.drawable.plaster_cast,
            R.drawable.iv_fluid_bag,
            R.drawable.plunger_of_syringe,
            R.drawable.shoe_cover,
            R.drawable.specimen,
            R.drawable.sature_needle,
            R.drawable.syringe_without_needle,
            R.drawable.urobag,
            R.drawable.vaccine,
            R.drawable.vacutainer,
            R.drawable.vacutainer_needle,
            R.drawable.iv_set,
            R.drawable.venflon,
            R.drawable.plastic_disposable_bin,
            R.drawable.vials,
            R.drawable.soiled_cotton_guaze,
            R.drawable.antibiotics
    };

    public static Integer[] id_ = {0, 1, 2,3,4,5,6,7};
}
