package com.example.medibin.bindata;


import com.example.medibin.R;

public class LabourWardData {

    public static String[] nameArray = {
            "Aborted Fetus",
            "Ampules",
            "Antibiotic Injection",
            "Blood Stained Cotton Guaze",
            "Broken Glassware",
            "Cap",
            "Disinfectant",
            "Empty Medicinal Glassware",
            "Empty Medicine Bottle Plastic",
            "Expired Medicines",
            "Face Mask",
            "Farmalin",
            "Foley's Catheter",
            "Gloves Pair",
            "Hospital Grown",
            "IM Needle",
            "IV Cannula",
            "IV Dextrose Bottle",
            "IV Fluids",
            "Cotton Guaze",
            "Kidner Tray Plastic",
            "Lancet",
            "Uro-Bag",
            "LP Needle",
            "Antibiotic",
            "Metal Cap of Vials",
            "Oxygen or Nebulizer Mask",
            "Placenta",
            "Plastic Covers",
            "Plunger of Syringe",
            "Suture Needle",
            "Soiled Cotton",
            "IV Fluid Bag",
            "Soiled Mastress",
            "Vials",
            "Stained Cotton and Guaze pads",
            "Syringe without Needle",
            "Soiled Dressing",
            "Vacutainer",
            "Disposable Shoe Cover",
            "Needles",
            "Blood Bags",
            "Lancet",
            "IV Normal Saline Bottle",
            "Medicine Vials and Ampules",
            "Insulin Syring",
            "Soiled Cotton Guaze",
            "Plastic Disposable Bin",
            "IV Set",
            "Specimen"



    };
    public static String[] versionArray = {
            "3",
            "1",
            "3",
            "3",
            "1",
            "3",
            "3",
            "1",
            "2",
            "3",
            "3",
            "3",
            "2",
            "2",
            "3",
            "4",
            "4",
            "2",
            "2",
            "3",
            "2",
            "4",
            "2",
            "4",
            "3",
            "4",
            "2",
            "3",
            "2",
            "2",
            "4",
            "3",
            "2",
            "3",
            "1",
            "3",
            "2",
            "3",
            "2",
            "3",
            "4",
            "3",
            "4",
            "2",
            "1",
            "4",
            "3",
            "2",
            "2",
            "3"



    };

    public static Integer[] drawableArray = {
            R.drawable.aborted_fetus,
            R.drawable.ampules,
            R.drawable.antibiotic_injection,
            R.drawable.blood_stained_cotton_guaze,
            R.drawable.broken_glassware,
            R.drawable.cap,
            R.drawable.disinfectant,
            R.drawable.empty_medicinal_glassware,
            R.drawable.empty_medicine_bottle_plastic,
            R.drawable.expired_or_discarded_medicines,
            R.drawable.face_mask,
            R.drawable.formalin,
            R.drawable.foleys_catheter,
            R.drawable.gloves_pair,
            R.drawable.hospital_gown,
            R.drawable.im_needle,
            R.drawable.iv_cannula,
            R.drawable.iv_dextrose_bottle,
            R.drawable.iv_fluids,
            R.drawable.cotton_guaze,
            R.drawable.kidner_tray_palstic,
            R.drawable.lancet,
            R.drawable.urobag,
            R.drawable.lp_needle,
            R.drawable.antibiotics,
            R.drawable.metal_cap_of_vials,
            R.drawable.oxygen_or_nebulizer_mask,
            R.drawable.placenta,
            R.drawable.plastic_covers,
            R.drawable.plunger_of_syringe,
            R.drawable.sature_needle,
            R.drawable.soiled_cotton,
            R.drawable.iv_fluid_bag,
            R.drawable.soiled_matress,
            R.drawable.vials,
            R.drawable.stained_cotton_and_guaze_pads,
            R.drawable.syringe_without_needle,
            R.drawable.soiled_dressing,
            R.drawable.vacutainer,
            R.drawable.shoe_cover,
            R.drawable.needles,
            R.drawable.blood_bags,
            R.drawable.lancet_1,
            R.drawable.iv_normal_saline_bottle,
            R.drawable.medicine_vials_and_ampules,
            R.drawable.insulin_syringe,
            R.drawable.soiled_cotton_guaze,
            R.drawable.plastic_disposable_bin,
            R.drawable.iv_set,
            R.drawable.specimen,


    };

    public static Integer[] id_ = {0, 1};
}
