package com.example.medibin.bindata;


import com.example.medibin.R;

public class OperationTheatreData {

    public static String[] nameArray = {
            "Aborted Fetus",
            "Ampules",
            "Amputated Body Parts",
            "ET Tube",
            "Aspirated Secretion",
            "Biopsy Needle",
            "Biopsy Specimen",
            "Dialysis Catheter",
            "Blood Stained Cotton Guaze",
            "Bone Marrow Biopsy Needle",
            "Cap",
            "Cotton Guaze",
            "Dental Implants",
            "Antibiotic Injection",
            "Empty Medicine Bottle Plastic",
            "Venflon",
            "Microscope Slides",
            "Face Mask",
            "Foleys Catheter",
            "Gloves Pair",
            "IV Cannula",
            "Human Anatomical Waste",
            "IM Needle",
            "Blood Bags",
            "IV Dextrose Bottle",
            "Expired Medicines",
            "Hospital Grown",
            "Kidner Tray Plastic",
            "Liver Biopsy Needle",
            "LP Needle",
            "Medicine Vials and Ampules",
            "Metal Cap of Vials",
            "Metal Implants",
            "Soiled Cotton Guaze",
            "Metallic Body Implants",
            "Nasogastric Tube",
            "Needles",
            "Oxygen or Nebulizer Mask",
            "Placenta",
            "Plaster Cast",
            "Plastic Covers",
            "Plastic Disposable Bin",
            "Plunger of Syringe",
            "Suture Needle",
            "Shoe Cover",
            "Slide & Cover Slip",
            "Smear",
            "Soiled Mastress",
            "Tracheostomy Tube",
            "Soiled Dressing",
            "Vacutainer Needle",
            "Specimen",
            "IV Set",
            "Surgical Blade  & Scalpel",
            "Syringe without Needle",
            "Test Tubes",
            "Tooth",
            "Soiled Cotton",
            "Uro-Bag",
            "Metallic Body Implant",
            "Vacutainer",
            "Stained Cotton and Guaze pads",
            "IV Fluid Bag"
    };
    public static String[] versionArray = {
            "3",
            "1",
            "3",
            "2",
            "3",
            "4",
            "3",
            "2",
            "3",
            "4",
            "3",
            "3",
            "1",
            "3",
            "2",
            "4",
            "1",
            "3",
            "2",
            "2",
            "4",
            "3",
            "4",
            "3",
            "2",
            "3",
            "3",
            "2",
            "4",
            "4",
            "1",
            "4",
            "1",
            "3",
            "1",
            "2",
            "4",
            "2",
            "3",
            "3",
            "2",
            "2",
            "2",
            "4",
            "3",
            "1",
            "1",
            "3",
            "2",
            "3",
            "4",
            "3",
            "2",
            "4",
            "2",
            "1",
            "3",
            "3",
            "2",
            "1",
            "2",
            "3",
            "2",
    };

    public static Integer[] drawableArray = {
            R.drawable.aborted_fetus,
            R.drawable.ampules,
            R.drawable.amputated_body_parts,
            R.drawable.et_tube,
            R.drawable.aspirated_secretion,
            R.drawable.biopsy_needle,
            R.drawable.biopsy_specimen,
            R.drawable.dialysis_catheter,
            R.drawable.blood_stained_cotton_guaze,
            R.drawable.bone_marrow_biopsy_needle,
            R.drawable.cap,
            R.drawable.cotton_guaze,
            R.drawable.dental_implants,
            R.drawable.antibiotic_injection,
            R.drawable.empty_medicine_bottle_plastic,
            R.drawable.venflon,
            R.drawable.microscope_slides,
            R.drawable.face_mask,
            R.drawable.foleys_catheter,
            R.drawable.gloves_pair,
            R.drawable.iv_cannula,
            R.drawable.human_anatomical_waste,
            R.drawable.im_needle,
            R.drawable.blood_bags,
            R.drawable.iv_dextrose_bottle,
            R.drawable.expired_or_discarded_medicines,
            R.drawable.hospital_gown,
            R.drawable.kidner_tray_palstic,
            R.drawable.liver_biopsy_needle,
            R.drawable.lp_needle,
            R.drawable.medicine_vials_and_ampules,
            R.drawable.metal_cap_of_vials,
            R.drawable.metal_implants,
            R.drawable.soiled_cotton_guaze,
            R.drawable.metallic_body_implants,
            R.drawable.nasogastric_tube,
            R.drawable.needles,
            R.drawable.oxygen_or_nebulizer_mask,
            R.drawable.placenta,
            R.drawable.plaster_cast,
            R.drawable.plastic_covers,
            R.drawable.plastic_disposable_bin,
            R.drawable.plunger_of_syringe,
            R.drawable.sature_needle,
            R.drawable.shoe_cover,
            R.drawable.slides,
            R.drawable.blood_smear,
            R.drawable.soiled_matress,
            R.drawable.tracheostomy_tube,
            R.drawable.soiled_dressing,
            R.drawable.vacutainer_needle,
            R.drawable.specimen,
            R.drawable.iv_set,
            R.drawable.surgical_blade_scalpel,
            R.drawable.syringe_without_needle,
            R.drawable.test_tubes,
            R.drawable.tooth,
            R.drawable.soiled_cotton,
            R.drawable.urobag,
            R.drawable.metallic_body_implants,
            R.drawable.vacutainer,
            R.drawable.stained_cotton_and_guaze_pads,
            R.drawable.iv_fluid_bag,
    };

    public static Integer[] id_ = {0, 1, 2, 3, 4, 5, 6};
}
