package com.example.medibin.bindata;


import com.example.medibin.R;

public class OutPatientWardData {

    public static String[] nameArray = {
            "Broken Glassware",
            "Dental Implant",
            "Face Mask",
            "Kidner Tray Plastic",
            "Nasogastic Tube",
            "Plastic Disposable Bin",
            "Insulin Syringe",
            "Lancet",
            "Oxygen Nebulizer mask",
            "Slides",
            "Syringe without Needle",
            "Vaccine vial",
            "Aspirated body Fluids",
            "Cap",
            "Empty Medical Glassware",
            "Fixed Needle syringe",
            "IV normal Saline Bottle",
            "Metal cap of Vials",
            "Plastic covers",
            "Soiled cotton guaze",
            "Tooth",
            "Vacutainer",
            "Blood Smear",
            "Cotton Guaze",
            "Empty Medicine Bottle Plastic",
            "Gloves Pair",
            "Suture Needle",
            "Vaccine Syringe"
    };
    public static String[] versionArray = {
            "1",
            "1",
            "3",
            "2",
            "2",
            "2",
            "4",
            "4",
            "2",
            "1",
            "2",
            "3",
            "3",
            "3",
            "1",
            "4",
            "2",
            "4",
            "2",
            "3",
            "3",
            "2",
            "1",
            "3",
            "2",
            "2",
            "4",
            "4"
    };

    public static Integer[] drawableArray = {
            R.drawable.broken_or_discarded_glassware,
            R.drawable.dental_implant,
            R.drawable.face_mask,
            R.drawable.kidner_tray_palstic,
            R.drawable.nasogastric_tube,
            R.drawable.plastic_disposable_bin,
            R.drawable.insulin_syringe,
            R.drawable.lancet,
            R.drawable.oxygen_nebulizer_mask,
            R.drawable.slides,
            R.drawable.syringe_without_needle,
            R.drawable.vaccine_vial,
            R.drawable.aspirated_body_fluids,
            R.drawable.cap,
            R.drawable.empty_medicinal_glassware,
            R.drawable.fixed_needle_syringe,
            R.drawable.iv_normal_saline_bottle,
            R.drawable.metal_cap_of_vials,
            R.drawable.plastic_covers,
            R.drawable.soiled_cotton_guaze,
            R.drawable.tooth,
            R.drawable.vacutainer,
            R.drawable.blood_smear,
            R.drawable.cotton_guaze,
            R.drawable.empty_medicine_bottle_plastic,
            R.drawable.gloves_pair,
            R.drawable.sature_needle,
            R.drawable.vaccine_syringe};

    public static Integer[] id_ = {0, 1, 2};
}
